### ISSUE TITLE
No support for Metadata "tags" parameters

### ISSUE THREAD

**Issue by dammitjanet** [ideal-postcodes/openapi#29]
Currently the Keys API (KeyUsage) is the only method to support[tags metadata](https://docs.ideal-postcodes.co.uk/docs/guides/tags) but that is one lf the functions of that endpoint to query by tags.

All other methods where relevant do not have support for passing tags

> Tagging is only available via methods that drain your balance such as postcode or address search. Unsuccessful requests (i.e. non-2000 responses) do not affect your balance and so cannot be tagged.

This should be implemented for completeness

**Comment by cblanc** [comment]
Thanks @dammitjanet - should be fixed by #30
